export const FETCH_POKEMONS_SUCCESS = "FETCH_POKEMONS_SUCCESS";
export const FETCH_POKEMONS_FAILURE = "FETCH_POKEMONS_FAILURE";

export const FETCH_POKEMONDETAILS_SUCCESS = "FETCH_POKEMONDETAILS_SUCCESS";
export const FETCH_POKEMONDETAILS_FAILURE = "FETCH_POKEMONDETAILS_FAILURE";

export const FETCH_TYPES_SUCCESS = "FETCH_TYPES_SUCCESS";
export const FETCH_TYPES_FAILURE = "FETCH_TYPES_FAILURE";

export const CREATE_POKEMON_SUCCESS = "CREATE_POKEMON_SUCCESS";
export const CREATE_POKEMON_FAILURE = "CREATE_POKEMON_FAILURE";
