export const FETCH_POKEMONS_SUCCESS = "FETCH_POKEMONS_SUCCESS";
export const FETCH_POKEMONS_FAILURE = "FETCH_POKEMONS_FAILURE";

export const FETCH_POKEMONDETAILS_SUCCESS = "FETCH_POKEMONDETAILS_SUCCESS";
export const FETCH_POKEMONDETAILS_FAILURE = "FETCH_POKEMONDETAILS_FAILURE";
