export const FETCH_POKEMONS_SUCCESS = "FETCH_POKEMONS_SUCCESS";
export const FETCH_POKEMONS_FAILURE = "FETCH_POKEMONS_FAILURE";

export const FETCH_POKEMONDETAILS_SUCCESS = "FETCH_POKEMONDETAILS_SUCCESS";
export const FETCH_POKEMONDETAILS_FAILURE = "FETCH_POKEMONDETAILS_FAILURE";

export const FETCH_TYPES_SUCCESS = "FETCH_TYPES_SUCCESS";
export const FETCH_TYPES_FAILURE = "FETCH_TYPES_FAILURE";

export const CREATE_POKEMON_SUCCESS = "CREATE_POKEMON_SUCCESS";
export const CREATE_POKEMON_FAILURE = "CREATE_POKEMON_FAILURE";

export const SORT_POKEMONS_BY_NAME = "SORT_POKEMON_BY_NAME";

export const SORT_POKEMONS_BY_ATTACK = "SORT_POKEMON_ATTACK";

export const FILTER_POKEMON_BY_ORIGIN = "FILTER_POKEMON_BY_ORIGIN";

export const FILTER_POKEMON_BY_TYPE = "FILTER_POKEMON_BY_TYPE";